version: '3'
services:
  
  postgres-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    volumes:
        # Here you should paste a path (directory) where 
        # postgres-db container will persist its data.
      - /var/docker_data/simple_monero_donation_service/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  monero-rpc:
    image: chekist32/monero-wallet-rpc:v0.18.3.1
    restart: unless-stopped
    ports:
      - 38083:38083
    volumes:
        # Here you should paste a path (directory) where the view-only monero wallet is located.
      - /var/docker_data/simple_monero_donation_service/monero/wallets/test1_wallet:/monero/wallet
    command:
        # For reference see: https://github.com/chekist32/monero-wallet-rpc-docker/blob/master/docs/monero-wallet-rpc-man.md
      - "--stagenet" 
      - "--daemon-address=stagenet.community.rino.io:38081"
      - "--trusted-daemon" 
      - "--rpc-bind-port=38083" 
      - "--rpc-login=user:pass" 
      - "--wallet-dir=/monero/wallet"

  backend:
    image: chekist32/simple-xmr-donation-service-backend:v0.5.0
    env_file:
        # Here you can paste a path to the .env file for backend container.
        # Example can be found under backend/env.example
      - ./backend/.env.dev
    ports:
      - 8081:8080
    depends_on:
      - monero-rpc
      - postgres-db

  frontend-client:
    build:
      context: ./frontend
      dockerfile: client/Dockerfile
      args:
          # A url mapped to the backend container
        - API_BASE_URL=http://localhost:8081
    ports:
      - "81:80"
    depends_on:
      - backend

  frontend-admin:
    build:
      context: ./frontend
      dockerfile: admin-panel/Dockerfile
      args:
          # A url mapped to the backend container
        - API_BASE_URL=http://localhost:8081
    ports:
      - "82:80"
    depends_on:
      - backend
