pipeline {
    agent {
        docker { image 'maven:3.9.6-eclipse-temurin-21-alpine'}
    }

    environment {
        MAVEN_LOCAL_REPO = "${WORKSPACE}/.m2/repository"
    }

    stages {
        stage("Test") {
            steps {
                echo "Test"
                sh 'mvn --version'
                sh 'cd backend && mvn dependency:go-offline test'
            }
        }
        stage("Build") {
            steps {
                echo "Build"
                sh 'java --version'
            }
        }
        stage("Deploy") {
            steps {
                echo "Deploy"
            }
        }
    }
}